
[package]
name = "blocadamia"
version = "1.0.0"
authors = []

[addresses]
blocadamia_addr = "0x9f5c1bc6345eeb5c7ee48e51c46143b82dbea8af58484a6d76da16164e7d7316"

[dev-addresses]
blocadamia_addr = "0x9f5c1bc6345eeb5c7ee48e51c46143b82dbea8af58484a6d76da16164e7d7316"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"
